### ISSUE TITLE
Inscripciones: debe permitir editarse

### ISSUE THREAD

**Issue by dcorvetto** [jcmontx/seminare_tpo#18]
Al ir a inscripcion y buscar alumno, carga los datos existentes. Si modifico los datos, debe actualizarlos y no crear una nueva inscripcion

**Comment by jcmontx** [comment]
ah puede haber una sola inscripción por alumno?

**Comment by dcorvetto** [comment]
No, pero si elijo mismo curso y alumno y modifico datos, no pasa nada - veo mensaje en la api que se llama pero no se muestra esta info, y debe permitir modificar la data de cualquier forma (si agrego que entregó documentación por ejemplo)

**Comment by dcorvetto** [comment]
No debería a su vez permitir al alumno anotarse en 1er y 2do año (dos cursos activos).
